### ISSUE TITLE
Request: Add tap_action

### ISSUE THREAD

**Issue by davidgdlt** [luixal/lovelace-media-source-image-card#1]
Thanks for writing this custom card! I got here from this post:
https://community.home-assistant.io/t/image-in-media-browser-on-picture-card/292457/14

Not sure how difficult this would be to implement, but it would be great if this card supported tap actions, ie. to be able to call a service with a tap on the image as supported in other cards. Something like:

tap_action:
  action: call-service
  service: camera.turn_on
  data: {}
  target:
    entity_id: camera.my_camera

**Comment by luixal** [comment]
Hi!

Glad you enjoy it!

That was something I planned to include, but being just for my use, I didn't code it.

I will add this, possibly in the same style [mushroom cards do](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/template.md). The config would be just as you stated above :)

Cheers :)

**Comment by davidgdlt** [comment]
Thanks!

**Comment by luixal** [comment]
Hi @davidgdlt , I've implemented these changes. You can download the [last release](https://github.com/luixal/lovelace-media-source-image-card/releases/tag/v0.1.1) (0.1.1), already published for HACS.

You can find the info about using `call-service` in the readme, in the [Actions section here](https://github.com/luixal/lovelace-media-source-image-card#call-service).

Let me know if that works for you :)

**Comment by davidgdlt** [comment]
Just tried it and it works like a charm. Thanks again for taking the time to implement it!
Cheers

**Comment by luixal** [comment]
No needed, thank you for using the card :)
