### ISSUE TITLE
bug: `media-source://` can't be a part of template

### ISSUE THREAD

**Issue by 532910** [luixal/lovelace-media-source-image-card#10]
this works:
```
image: media-source://{{ states("sensor.photo") }}
```
with template sensor's template set to
```
media_source/local/share/{{ '%02d' % range(0, 20) | random }}.jpeg
```

this does not:
```
image: {{ states("sensor.photo") }}
```
with template sensor's template set to
```
media-source://media_source/local/share/{{ '%02d' % range(0, 20) | random }}.jpeg
```

**Comment by luixal** [comment]
Umm... not sure, haven't tested, but using `media-source://` string in a template sensor should work.

Can you paste some examples and the resolved string from the template? If you can paste the error shown in the card, the better.

Thanks!

**Comment by 532910** [comment]
no error, just nothing is shown
could you try it to check, please
template is resolved correcty

**Comment by 532910** [comment]
![image](https://github.com/luixal/lovelace-media-source-image-card/assets/14617699/5270442f-f167-4a6d-b9e3-f56351886b79)
![image](https://github.com/luixal/lovelace-media-source-image-card/assets/14617699/39f4c4b1-8f35-4b06-8046-ad1d237ef9d0)
![image](https://github.com/luixal/lovelace-media-source-image-card/assets/14617699/8007afb4-096c-45ed-a9f6-43670b5bdd88)

**Comment by luixal** [comment]
Thanks for the info, I got your point.

In your card config, instead of:

```yaml
image: "{{ states('sensor.test') }}"
```

it was intented to be like this:

```yaml
image: |
  {{ states('sensor.test') }}
```

anyway, it doesn't work either as it tries to load the url as a public image instead of a media source one.

I already have an idea of what's going on, but I will look into this and publish a fix.

Thanks!

**Comment by luixal** [comment]
Hi,

I just release v0.2.5 that should fix this, can you update and try it out?

Thanks!

**Comment by 532910** [comment]
Yep, can confirm it works now as expected!
