### ISSUE TITLE
double media-source in the url

### ISSUE THREAD

**Issue by 532910** [luixal/lovelace-media-source-image-card#11]
What is the reason for doubling `media-source`?
Could it be `media-source://share_name/image.jpeg` instead of `media-source://media-source/local/share_name/image.jpeg`?

**Comment by luixal** [comment]
I don't know a lot about how HA handles this paths. I could have hardcoded the `media-source://media-source/local` slice of the path, but I prefered to let it to the user.

This card can also show `regular` images so another option for adding that slice would have been needed.

**Comment by 532910** [comment]
I found this format in home-assistant docs:
https://www.home-assistant.io/integrations/media_source/#playing-media-from-a-media-source

So my question about doubling is not valid.
