### ISSUE TITLE
Caption

### ISSUE THREAD

**Issue by cagnulein** [luixal/lovelace-media-source-image-card#14]
would be nice to add also a caption in the image!
Thanks for your work!

**Comment by luixal** [comment]
Something like this can be easily achieved using more cards:

![image](https://github.com/user-attachments/assets/1ec6dc4c-aa04-4bff-b6c1-320f4ce00f8d)

or do you mean a different thing?

**Comment by cagnulein** [comment]
Yes this would be OK. So I can concatenate more cards? I didn't know

**Comment by cagnulein** [comment]
Do you mean something like this https://github.com/custom-cards/stack-in-card ?

**Comment by luixal** [comment]
Somehow I forgot answering to this.

Yes, you can use stack-in-card or custom:button-card and there you can make almost everything you can think of :)
