### ISSUE TITLE
Google Photos

### ISSUE THREAD

**Issue by minermartijn** [luixal/lovelace-media-source-image-card#16]
Now that home assistant can upload to and view from Google Photos.
I was wondering if this is possible with your image card?

Not sure where to point the media url at now.
When i open up the media, i can see Google Photos/My name/My album and then the photos.

Hopefully i can use those images, because that would be awesome for our family!

**Comment by luixal** [comment]
Have you tried something like:

```yaml
type: custom:media-source-image-card
image: "media-source://media_source/local/Google Photos/My name/My album/my_picture.png"
```
Media source path are kind of messy...
