### ISSUE TITLE
doesn't seem to work for non "local" media-sources

### ISSUE THREAD

**Issue by armedad** [luixal/lovelace-media-source-image-card#7]
to be clear, the files are still local in homeassistant.  it just mean it's not specified under media-sources://media_source/local/...   

i'm specifying: 
image: media-source://media_source/photos/test.jpg

in my configuration.yaml i have this:
```
  media_dirs:
    media: "/media"
    photos: /media/cc_haimages
```

w/ samba i have a test.jpg on \\homeassistant\media\cc_haimages\test.jpg

but the image doesn't show. 

i do see this image using other cards e.g. custom:gallery-card and browser_mod
so i'm pretty sure i've got the config right..   but this media-source-image-card doesn't seem to be able to find the image.

note that it *does* recognize the path. if i change "photos" to "bogus" it properly complains that no such folder exists.

**Comment by luixal** [comment]
Hi,

Which uri/url are you using in the orher cards that show the image?

I don't this scenario at home, but I can reproduce easily, just to be clear: you have a samba shared dir in your network and you're mapping it in home assistant? or do you have a dir in home assistant you're sharing using samba?

Thanks!

**Comment by luixal** [comment]
I guess this was related to an error that I recently fix in version v.0.2.3.

Can you give it a try?

**Comment by armedad** [comment]
sorry i missed you message last week.  i'll give it a try tonight!

**Comment by armedad** [comment]
looks good.  thanks!

**Comment by luixal** [comment]
Great! I'm closing this :)
